name: orchid_classifier
description: "App phân loại giống hoa lan sử dụng AI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_markdown: ^0.7.3
  url_launcher: ^6.3.0
  image_cropper: ^9.0.0
  path_provider: ^2.1.4

  
  http: ^1.2.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  share_plus: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/classifier/data/infor/
    - lib/classifier/data/category/class0000/
    - lib/classifier/data/category/class0001/
    - lib/classifier/data/category/class0002/
    - lib/classifier/data/category/class0003/
    - lib/classifier/data/category/class0004/
    - lib/classifier/data/category/class0005/
    - lib/classifier/data/category/class0006/
    - lib/classifier/data/category/class0007/
    - lib/classifier/data/category/class0008/
    - lib/classifier/data/category/class0009/
    - lib/classifier/data/category/class0010/
    - lib/classifier/data/category/class0011/
    - lib/classifier/data/category/class0012/
    - lib/classifier/data/category/class0013/
    - lib/classifier/data/category/class0014/
    - lib/classifier/data/category/class0015/
    - lib/classifier/data/category/class0016/
    - lib/classifier/data/category/class0017/
    - lib/classifier/data/category/class0018/
    - lib/classifier/data/category/class0019/
    - lib/classifier/data/category/class0020/
    - lib/classifier/data/category/class0021/
    - lib/classifier/data/category/class0022/
    - lib/classifier/data/category/class0023/
    - lib/classifier/data/category/class0024/
    - lib/classifier/data/category/class0025/
    - lib/classifier/data/category/class0026/
    - lib/classifier/data/category/class0027/
    - lib/classifier/data/category/class0028/
    - lib/classifier/data/category/class0029/
    - lib/classifier/data/category/class0030/
    - lib/classifier/data/category/class0031/
    - lib/classifier/data/category/class0032/
    - lib/classifier/data/category/class0033/
    - lib/classifier/data/category/class0034/
    - lib/classifier/data/category/class0035/
    - lib/classifier/data/category/class0036/
    - lib/classifier/data/category/class0037/
    - lib/classifier/data/category/class0038/
    - lib/classifier/data/category/class0039/
    - lib/classifier/data/category/class0040/
    - lib/classifier/data/category/class0041/
    - lib/classifier/data/category/class0042/
    - lib/classifier/data/category/class0043/
    - lib/classifier/data/category/class0044/
    - assets/images/ckiu6.jpg

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ckiu6.jpg"